cookie:
  expiry_days: 30
  key: some_signature_key
  name: promon_ai_chatbot
credentials:
  usernames:
    pparker:
      email: pparker@example.com
      name: Peter Parker
      password: abc123
    rmiller:
      email: rmiller@example.com
      name: Rebecca Miller
      password: def456
    mdaros:
      email: mdaros@example.com
      name: Michel Daros
      password: michelpassword
    gpelissaro:
      email: gpelissaro@example.com
      name: Gustavo Pelissaro
      password: gustavopassword
    asandoval:
      email: asandoval@example.com
      name: Alex Sandoval
      password: alexpassword
    amendes:
      email: amendes@example.com
      name: Alexsandra Mendes
      password: alexsandrapassword
    mlamim:
      email: mlamim@example.com
      name: Marco Lamim
      password: marcopassword
    ggrandesi:
      email: ggrandesi@example.com
      name: Guilherme Grandesi
      password: guilherme123
    hriego:
      email: hriego@example.com
      name: Henrique Riego
      password: henrique123
    rishikawa:
      email: rishikawa@example.com
      name: Rogerio Ishikawa
      password: rogerio123
    dandrade:
      email: dandrade@example.com
      name: David Andrade
      password: david123
    fgarcia:
      email: fgarcia@example.com
      name: Fabiana Garcia
      password: fabiana123
    gsouza:
      email: gsouza@example.com
      name: Gabriela Souza
      password: gabriela123
    ahiroshi:
      email: ahiroshi@example.com
      name: Andre Hiroshi
      password: andre123
    rpereira:
      email: rpereira@example.com
      name: Rafael Pereira
      password: rafael123
    gduarte:
      email: gduarte@example.com
      name: Gisele Duarte
      password: giselepassword
    brufino:
      email: brufino@example.com
      name: Bruna Rufino
      password: brunapassword
    hvitali:
      email: hvitali@example.com
      name: Hellen Vitali
      password: hellenpassword
    rbretzel:
      email: rbretzel@example.com
      name: Rosana Bretzel
      password: rosanapassword
    maraujo:
      email: maraujo@example.com
      name: Maria Araujo
      password: mariapassword
